import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main>
        <div className="container py-5 text-center">
          <h1 className="mt-5 display-1">
            O melhor jeito de comprar o que você ama
          </h1>
          <p className="my-4">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae
            iusto voluptatem obcaecati omnis error architecto neque cum
            exercitationem fugiat. Vero illo autem eum nisi sapiente, odio optio
            accusamus cupiditate ad.
          </p>
          <Link href="/products">
            <button className="btn bg-light px-4 pb-2 text-dark">
              Conheça nossos produtos!
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
